### ISSUE TITLE
Combination with compression-plugin possible?

### ISSUE THREAD

**Issue by kuhnroyal** [Klathmon/imagemin-webpack-plugin#29]
I am trying to use this with the compression plugin, but no matter how I order the plugins, the compression-plugin always compresses the original source-image and not the minified image. Any ideas?

```
            new ImageminPlugin(),
            new CompressionPlugin({
                test: /\.js$|\.html$|\.css$|\.svg$|\.png$|\.ttf$|\.woff$|\.woff2$|\.gif$/,
                algorithm: "gzip",
                threshold: 1024,
                minRatio: 0.8
            }),
```

**Comment by Klathmon** [comment]
I'd guess it's most likely because of the compiler event this plugin works on is after the event the compression plugin works on.

If you play around with the event on [this line](https://github.com/Klathmon/imagemin-webpack-plugin/blob/7d6b05d56b2cdb198ae6847d543adb8e7fb2bf59/index.js#L69) you will most likely be able to get it working before the compression plugin which means it will pick up the minified imges.

But as a quick PSA...

You generally don't want to compress images as they are already compressed in most formats. So gzipping a PNG file will generally not net you any savings and may actually increase the size as well as heavily increasing the CPU needed to decode the image 2 times.

**Comment by kuhnroyal** [comment]
Yea, you are probably right. Thank you.

**Comment by damianobarbati** [comment]
+1 for this one
