### ISSUE TITLE
Using externalImages with destination folder fails

### ISSUE THREAD

**Issue by taylorhoward92** [Klathmon/imagemin-webpack-plugin#46]
I'm using this plugin with Webpack and Laravel Mix on external files and when I only specify sources, it works fine and makes changes on files in place but when I specify a destination, the source and destination get concatenated together and an error is thrown.

Config:
```
new ImageminWebpackPlugin({
            externalImages: {
                sources: glob.sync('resources/assets/img/*.svg'),
                destination: 'public/img'
            },
            svgo: {
                plugins: [
                    { removeTitle: true }
                ]
            }
        })
```

Error:
```
94% asset optimizationError: ENOENT: no such file or directory, open 'public/img/resources/assets/img/icon-logo.svg'
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ development: `cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js`
```

Can someone confirm if this is something to do with my usage with Laravel Mix or if it is actually a imagemin-webpack issues?

**Comment by taylorhoward92** [comment]
Was using relative not absolute paths

**Comment by Klathmon** [comment]
That error is from the plugin trying to open the image `public/img/resources/assets/img/icon-logo.svg` and either not being able to, or it not existing.

Check that the file it is complaining about on the `ENOENT` line actually exists and is readable by webpack.

I'm going to close this issue now, but if it looks like the file should be there, i'll reopen it for you.

Also, I'm going to create a new issue for improving error messages, because that error is entirely unhelpful!
