### ISSUE TITLE
Exclude specific file

### ISSUE THREAD

**Issue by Jack89ita** [Klathmon/imagemin-webpack-plugin#69]
Hello! i'm currently using your plugin and i find it wonderful, but in my latest project i had the need to exclude some specific images because my team didn't want the compressed size but the full one.
Is there a way to achive this goal? Maybe passing an array of custom images to exclude.
Thank you very much!

**Comment by Klathmon** [comment]
You can use the `test` option to define either a regex, glob, a function, or an array of either of them to specify which files you want included.

You can use that to exclude some files from being minified. For example, if you wanted to include all files except for one named "notme.jpeg", you could put the test regex as `/^(?!notme).*/` which would match everything except for any file that has "notme" in the file path.

You can also do the same for globs if you find them easier, or you could even make it a function that takes the filename as the only argument and should return `true` if it keeps it, or `false` if it doesn't.

I hope that makes sense, and if you think it's overly complicated I can always look into adding an "exclude" option, but the logic behind what happens if `test` and a possible `exclude` option overlap is a little foggy to me, and I won't have time to get to anything for at least a week or 2...

Let me know if there's anything else you need!

**Comment by Klathmon** [comment]
Yeah that part isn't really spelled out well in the docs. I'd gladly take a PR that can improve that if you have time and don't mind! (no pressure though!)

I'm really bad with writing documentation, so any help that I can get I will gladly take!

Also, you are going to be the first person I know of that will use a function there, so if there are any problems or major performance issues or gotchas, i'd love a message back either here or in another Issue/PR letting me know so I can hopefully clean it up for you and others in the future!

Thanks

**Comment by tilvan** [comment]
@Klathmon Could you give a config example please? With function with exclude
