### ISSUE TITLE
Access the resource to create an image-specific hash

### ISSUE THREAD

**Issue by adrienharnay** [Klathmon/imagemin-webpack-plugin#72]
Hey,

I am currently using image-webpack-loader but am not very happy with it and would like to migrate to this library. Everything seems good, except I am doing this

```
            ({ resource }) => ({
              loader: 'image-webpack-loader',
              options: {
                mozjpeg: {
                  quality: 90,
                },
                pngquant: {
                  quality: '90-95',
                  speed: 1,
                },
                svgo: {
                  plugins: [
                    {
                      cleanupIDs: {
                        prefix: hash(resource),
                        minify: true,
                        remove: true,
                      },
                    },
                  ],
                },
              },
            }),
```

So that SVGs won't conflict between them. Is there a way to do the same thing with this library, that is to access the resource somehow?

Thanks in advance!

**Comment by Klathmon** [comment]
There isn't any way to do that through this plugin (without forking it and maintaining your own version), but you could do this by writing your own imagemin plugin.

It's not nearly as scary as it sounds, plugins are just a curried function that take a "config" object as the first argument, and the buffer as the second. So using es6 they look like this:

```
const myFirstImageminPlugin = (options) => async (resource) => {
  // optimize resource any way you want here!
  return resource // return the optimized resource when done
}
```

You can either manage the names on your own like that, or you can just wrap svgo kinda like this:
```
import svgo from 'imagemin-svgo'

const fancySvgo = (options) => async (resource) => {
  return svgo({
    ...options,
    plugins: [{
      cleanupIDs: {
      prefix: hash(resource),
      minify: true,
      remove: true,
    }]
  })(resource)
}
```

It won't be as fast due to having to re-init svgo for every file, but looking at [their source](https://github.com/imagemin/imagemin-svgo/blob/eba55fbcfc046cd25bd4f88bb4cc61926513feb2/index.js) I don't think it will make any difference at all.

To use the plugin you made, you'll set svgo to `null` in the `imagemin-webpack-plugin` options (to disable the builtin svgo plugin), then pass the `fancySvgo` function into the `plugins` array option in `imagemin-webpack-plugin`. Kinda like this:

```
    new ImageminPlugin({
      svgo: null,
      plugins: [
        fancySvgo({
          // any other svgo options you want go here
        }),
      ],
    })
```

All of the code in this comment is untested, so treat it more like a guideline or pseudocode rather than documentation or a working example. And take a look at imagemin plugins on npm (like [imagemin-svgo here](https://github.com/imagemin/imagemin-svgo/blob/eba55fbcfc046cd25bd4f88bb4cc61926513feb2/index.js) or [imagemin-pngquant here](https://github.com/imagemin/imagemin-pngquant/blob/be923c2841b8730c8fc73f70df3b9cf9ff909355/index.js) if you want an example of how the plugins work. They are really straightforward and easy to read for the most part.

And I hope that helps, feel free to comment again if you run into any issues, and if you figure it out and it works well for you, I'd love a documentation PR to explain the process a bit better for others (as well as any gotchas you run into). It's [Hacktoberfest](https://hacktoberfest.digitalocean.com/) so if you make a documentation PR for this, you'll be 1/5th of the way toward a free t-shirt!

**Comment by adrienharnay** [comment]
Thanks for the really nice explanations! I will try what you suggested and will tell you how it went! :+1:
