### ISSUE TITLE
Could not find a declaration file for module ' imagemin-webpack-plugin '

### ISSUE THREAD

**Issue by tr1s** [Klathmon/imagemin-webpack-plugin#73]
I'm finishing up my webpack4 boilerplate but I'm having no luck with imagemin.. then I realized it can't even find it in the node_modules. Is this a bug? I'm trying the npm audit fix and npm install @type thing in the message. Nothings working. I've deleted my node_modules and re-installed everything as well. Everything has been going smooth up until imagemin. Now there's 6 vulnerabilities and it's not working at all.

Any help would be greatly appreciated! As you can see in my pic the folders are in the node_modules.. they just won't connect I guess.

<img width="1260" alt="cleanshot 2018-11-19 at 00 06 03 2x" src="https://user-images.githubusercontent.com/19172250/48687427-63ae0600-eb8f-11e8-9df2-2bad6c119e63.png">

![hyper 2018-11-19 at 00 10 27 2x](https://user-images.githubusercontent.com/19172250/48687463-922be100-eb8f-11e8-90bd-36d8e5aca091.png)

![hyper 2018-11-19 at 00 10 17 2x](https://user-images.githubusercontent.com/19172250/48687464-922be100-eb8f-11e8-9b11-fe0c619c4753.png)

**Comment by Klathmon** [comment]
There are no typescript definitions for this project, and I don't have any plans at this time to create them (however I'd be happy to merge a PR with them). So that is why you are getting the [ts] error. I'm not very familiar with typescript, so you will have to do some research and see if  there is a way to mark this plugin as "untyped" or something similar.

As for the NPM audit issues, unfortunately this plugin uses `imagemin` plugins, which themselves use the vulnerable versions of software. If you use [`yarn`](https://yarnpkg.com/) then the problem is solve for you as I can force those transitive dependencies to not install, but with `npm` I cannot (or do not know how to at this time).

Luckily it's not a problem, as the code that caused the vulnerability is never run in this plugin, so even though the `npm audit` command is showing it as vulnerable, there is no way to actually run the code in question.

You can see more information [here](https://github.com/Klathmon/imagemin-webpack-plugin/issues/63).
