### ISSUE TITLE
Using peer dependencies for imagemin and imagemin plugins

### ISSUE THREAD

**Issue by thasmo** [Klathmon/imagemin-webpack-plugin#77]
Any reason not using peer dependencies for `imagemin` and it's plugins? Would be nice to define `imagemin` and plugin versions in a project.

**Comment by Klathmon** [comment]
Sorry I somehow missed this opening...

I don't use them as peer deps because I was trying to keep this easy to use. `yarn add --dev imagemin-webpack-plugin` is all you need, rather than requiring you to have the various optimizers installed yourself.

If you want, you can always install the plugins in your package.json, pass `null` in for all of the included optimizers, then include your versions in the `plugins` option. Because of how node_modules is laid out, my plugin will use the versions I included, but if you install them yourself, import them in your webpack file, then pass them into the `plugins` array, it will use the versions you specified!

I figured that would be a good compromise. The majority of people get the easy/fast path (just install and use), and for those that want more control, it's only one small step extra (passing `null` in for the built-in optimizer options, then including whatever ones you want in the `plugins` array).



I'm going to close this for now, but if you think i'm wrong and this should be revisited, please let me know and i'll be happy to re-open it so we can have a discussion! I'm not opposed to this change, but if i'm being honest I don't know a ton about peer-deps right now, so I don't know how it would impact users and what changes would be needed.
