### ISSUE TITLE
Do we track our image-cache in git? 

### ISSUE THREAD

**Issue by rv-egranger** [Klathmon/imagemin-webpack-plugin#84]
I'm honestly not sure. Should we gitignore our image cache? I'm leaning towards no, but I'd like to double check here and see if any maintainers have an opinion.

**Comment by Klathmon** [comment]
I'd say "absolutely not".

The caching mechanism in this plugin is super basic. It doesn't account for changed settings, changed plugin versions, or different platforms or anything. It's a super basic method of "hash file contents, if a file with that hash exists in the cache, use it, otherwise optimize the file", so it's not meant to be super long lived. It also never cleans any old cached files up, so it has the ability to grow to a stupid size.

I should probably put a warning about not committing the cache, because its' a super valid question!

I'm also open to improvements in the caching system, I think there are some super easy wins we could find (like hashing the options object as well as the file contents), but I just havent had the time to do it!

But overall, the cache is meant to be short-ish lived, and I personally set my cache folder in projects that I use this plugin in to `./node_modules/.imagemin-plugin-cache`. That way it's cleared somewhat often (obviously not daily, but at least monthly in most cases), and it's easy to clear and reinstall everything.
